######################################################################
#
# File name : ALU_tb_top_compile.do
# Created on: Sat Nov 01 23:32:50 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Applications\\questasim64_2024.1\\win64\\vlib questa_lib/work
D:\\Applications\\questasim64_2024.1\\win64\\vlib questa_lib/msim

D:\\Applications\\questasim64_2024.1\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\Applications\\questasim64_2024.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\Applications\\questasim64_2024.1\\win64\\vlog  -incr -mfcu -work xil_defaultlib  "+incdir+../../../../../RTL" "+incdir+../../../../../../../../../../Applications/Vivado_2025.1.1/2025.1.1/Vivado/data/rsb/busdef" "+incdir+../../../../RISC-V-RV32I.ip_user_files/ipstatic" \
"../../../../../RTL/ALU.v" \

D:\\Applications\\questasim64_2024.1\\win64\\vlog  -incr -mfcu -sv -work xil_defaultlib  "+incdir+../../../../../RTL" "+incdir+../../../../../../../../../../Applications/Vivado_2025.1.1/2025.1.1/Vivado/data/rsb/busdef" "+incdir+../../../../RISC-V-RV32I.ip_user_files/ipstatic" \
"../../../../../Simulation/ALU/ALU_interface.sv" \
"../../../../../Simulation/ALU/ALU_tb_top.sv" \

# compile glbl module
D:\\Applications\\questasim64_2024.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

