######################################################################
#
# File name : ALU_tb_wave.do
# Created on: Sun Nov 02 12:23:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
