######################################################################
#
# File name : ALU_tb_simulate.do
# Created on: Sun Nov 02 12:23:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib ALU_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ALU_tb_wave.do}

view wave
view structure
view signals

do {ALU_tb.udo}

run 1000ns
