######################################################################
#
# File name : Register_File_tb_compile.do
# Created on: Sun Nov 02 14:49:24 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Applications\\questasim64_2024.1\\win64\\vlib questa_lib/work
D:\\Applications\\questasim64_2024.1\\win64\\vlib questa_lib/msim

D:\\Applications\\questasim64_2024.1\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\Applications\\questasim64_2024.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\Applications\\questasim64_2024.1\\win64\\vlog  -incr -mfcu -work xil_defaultlib  "+incdir+../../../../../RTL" "+incdir+../../../../../../../../../../Applications/Vivado_2025.1.1/2025.1.1/Vivado/data/rsb/busdef" "+incdir+../../../../RISC-V-RV32I.ip_user_files/ipstatic" \
"../../../../../RTL/Register_File.v" \
"../../../../../Simulation/Register_File_tb.v" \


# compile glbl module
D:\\Applications\\questasim64_2024.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

