######################################################################
#
# File name : Register_File_tb_simulate.do
# Created on: Sun Nov 02 14:49:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib Register_File_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {Register_File_tb_wave.do}

view wave
view structure
view signals

do {Register_File_tb.udo}

run 1000ns
