######################################################################
#
# File name : Register_File_tb_wave.do
# Created on: Sun Nov 02 14:44:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
