######################################################################
#
# File name : Register_File_tb_elaborate.do
# Created on: Sun Nov 02 14:49:26 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Applications\\questasim64_2024.1\\win64\\vopt +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.Register_File_tb xil_defaultlib.glbl -o Register_File_tb_opt

quit -force
