@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Siemens Questa Advanced Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 02 12:23:28 +0800 2025
REM SW Build 6233196 on Thu Sep 11 21:27:30 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set bin_path=D:\\Applications\\questasim64_2024.1\\win64
call %bin_path%/vsim   -do "do {ALU_tb_simulate.do}" -l simulate.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
